### ISSUE TITLE
IOException when creating preference file

### ISSUE THREAD

**Issue by Adrodoc** [Energyxxer/Command-Block-Engine#1]
If the parent directory of the preference file cannot be created, for instance because the application has no permission to write to "C:\Program Files", any usage of the preference file will result in IOExceptions. This scenario is very likely as it can happen if the user is not an administrator or the operating system is not windows.
If the method call to [`mkdirs()`](https://github.com/Energyxxer/Command-Block-Engine/blob/36ad5851eced853ef1d9fc2f25e62eca4c0ba896/src/com/energyxxer/cbe/CBE.java#L26) returns false it might be a good idea to open a warning dialog or filechooser for the user.

To make this scenario highly unlikely consider to use `System.getProperty("user.home")` or refer to http://stackoverflow.com/questions/11113974/what-is-the-cross-platform-way-of-obtaining-the-path-to-the-local-application-da
If you don't want the CBE folder to show up in the user home you can hide it by using a dot `.` for the first character and call `Files.setAttribute(new File(Preferences.path).toPath(), "dos:hidden", true);`

It might also be a good idea to either use [`java.util.prefs.Preferences`](http://docs.oracle.com/javase/7/docs/api/java/util/prefs/Preferences.html) or [`java.util.Properties`](http://docs.oracle.com/javase/7/docs/api/java/util/Properties.html) to properly define the file format instead of manually writing a HashMap to the file.

**Comment by randomnetcat** [comment]
In a kind of related note...... this makes absolutely no attempt to support Linux :penguin:.

**Comment by Energyxxer** [comment]
Alright, I just switched to java.util.prefs.Preferences. It seems to be much easier to work with. Also, I've made most, if not all path strings use File.separator, instead of the usual slashes I was using. I'll push a commit later that includes these changes.
